# Generated by Django 5.2.6 on 2026-01-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_project_has_review_project_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
